name: Test docker image
on:
  workflow_run:
    workflows: ["Test build"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest

    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v3
      - name: Install Heroku CLI
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh
          heroku --version
      - name: login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_PASSWORD}}
      - name: Build and Push
        env:
          REACT_APP_FIREBASE_API_KEY: ${{secrets.REACT_APP_API_KEY}}
          REACT_APP_FIREBASE_APP_ID: ${{secrets.REACT_APP_FIREBASE_APP_ID}}
          REACT_APP_FIREBASE_AUTH_DOMAIN: ${{secrets.REACT_APP_FIREBASE_AUTH_DOMAIN}}
          REACT_APP_FIREBASE_MESSAGING_SENDER_ID: ${{secrets.REACT_APP_FIREBASE_MESSAGING_SENDER_ID}}
          REACT_APP_FIREBASE_PROJECT_ID: ${{secrets.REACT_APP_FIREBASE_PROJECT_ID}}
          REACT_APP_FIREBASE_STORAGE_BUCKET: ${{secrets.REACT_APP_FIREBASE_STORAGE_BUCKET}}
          REACT_APP_FIREBASE_ROOT_DIRECTORY: ${{secrets.REACT_APP_FIREBASE_ROOT_DIRECTORY}}
        run: 
          docker build . --build-arg REACT_APP_FIREBASE_API_KEY=$REACT_APP_FIREBASE_API_KEY --build-arg REACT_APP_FIREBASE_APP_ID=$REACT_APP_FIREBASE_APP_ID --build-arg REACT_APP_FIREBASE_AUTH_DOMAIN=$REACT_APP_FIREBASE_AUTH_DOMAIN --build-arg REACT_APP_FIREBASE_MESSAGING_SENDER_ID=$REACT_APP_FIREBASE_MESSAGING_SENDER_ID --build-arg REACT_APP_FIREBASE_PROJECT_ID=$REACT_APP_FIREBASE_PROJECT_ID --build-arg REACT_APP_FIREBASE_STORAGE_BUCKET=$REACT_APP_FIREBASE_STORAGE_BUCKET --build-arg REACT_APP_FIREBASE_ROOT_DIRECTORY=$REACT_APP_FIREBASE_ROOT_DIRECTORY -t ansarulsohan/huldra_test:latest -t ansarulsohan/huldra_test:${{github.run_number}} -t registry.heroku.com/host-tmp/web:latest && docker push ansarulsohan/huldra_test:latest && docker push ansarulsohan/huldra_test:${{github.run_number}}
      
      - name: Login to Heroku
        run: |
          heroku container:login
          docker push registry.heroku.com/${{vars.HEROKU_APP_NAME}}/web
          heroku container:release web --app host-tmp
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo 'The Triggering workflow failed. Terminating workflow'
