name: Lint on Push
on:
  push:
    branches:
      - "*"
      - "!dev"
      - "!main"
  pull_request:
    branches:
      - "dev"
      - "main"

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
      - name: Install dependencies
        run: npm ci
      - name: Lint files
        run: npm run lint
        env:
          CI: false
